[14.0][ADD] stock_picking_report_delivery_note: new module
nuobit/odoo-addons pull request #339
Opened 2023-11-20 18:55 UTC by KNVx

2023-11-21 18:00 UTC, eantones requested changes

2023-11-21 18:00 UTC, eantones commented on stock_picking_report_delivery_note/models/stock_picking.py
> +        self._get_lines()
Remove this line

2023-11-21 18:00 UTC, eantones commented on stock_picking_report_delivery_note/views/report_stock_picking_report_delivery_note.xml
> +<!--                                            <t t-set=""-->
Remove

2023-11-21 18:00 UTC, eantones commented on stock_picking_report_delivery_note/views/report_stock_picking_report_delivery_note.xml
> +                                        <!--                                        </t>-->
Remove

2023-11-21 18:00 UTC, eantones commented on stock_picking_report_delivery_note/views/report_stock_picking_report_delivery_note.xml
> +
Remove

2023-11-21 18:00 UTC, eantones commented on stock_picking_report_delivery_note_kit/__manifest__.py
> +    "installable": True,
Remove

2023-11-21 18:00 UTC, eantones commented on stock_picking_report_delivery_note_kit/__manifest__.py
> +    "summary": """Stock picking delivery note kit""",
Single quotes

2023-11-21 18:00 UTC, eantones commented on stock_picking_report_delivery_note_kit/README.rst
> +* Eric Antones <eantones@nuobit.com>
Add yourself here. In fact, create a readme folder and let the pre-commit do it for you

2023-11-21 18:00 UTC, eantones commented on stock_picking_report_delivery_note_kit/views/report_stock_picking_report_delivery_note.xml
> +            <t t-if="gm[1]">
It should be `parent_product` use `t-set`

2023-11-21 18:00 UTC, eantones commented on stock_picking_report_delivery_note_kit/views/report_stock_picking_report_delivery_note.xml
> +            <t t-set="move_lines" t-value="gm[0]" />
`t-set`

2023-11-21 18:00 UTC, eantones commented on stock_picking_report_delivery_note_kit/views/report_stock_picking_report_delivery_note.xml
> +                <div t-esc="gm[1].default_code" />
`t-set` everywhere

2023-11-21 18:00 UTC, eantones commented on stock_picking_report_delivery_note_kit/views/report_stock_picking_report_delivery_note.xml
> +                    <!--                    />-->
Remove

2023-11-22 11:32 UTC, KNVx commented
@eantones , request for a squash after review, before merge

2023-11-30 10:13 UTC, eantones requested changes
@KNVx

2023-11-30 15:04 UTC, eantones approved these changes

2024-03-04 20:45 UTC, merged