[14.0][ADD] stock_barcodes_serial_source_relocation: new module
nuobit/odoo-addons pull request #370
Opened 2024-02-15 11:23 UTC by FrankC013

2024-02-15 11:29 UTC, eantones approved these changes
Good job!!

2024-02-27 12:56 UTC, eantones requested changes

2024-02-27 12:56 UTC, eantones commented on stock_barcodes_serial_source_relocation/models/stock_barcodes_read.py
> +                            self.picking_id.picking_type_id.warehouse_id.id,
get_warehouse and check if the location has a warehouse

2024-02-27 12:56 UTC, eantones commented on stock_barcodes_serial_source_relocation/models/stock_picking_type.py
> +    @api.constrains("is_regularization")
add warehouse_id and the rest

2024-02-27 12:56 UTC, eantones commented on stock_barcodes_serial_source_relocation/models/stock_picking_type.py
> +                            ("is_regularization", "=", True),
add code

2024-02-27 12:56 UTC, eantones commented on stock_barcodes_serial_source_relocation/models/stock_barcodes_read.py
> +                            ("is_regularization", "=", True),
add company

2024-02-29 18:49 UTC, FrankC013 commented
@eantones This morning's changes

2024-02-29 23:00 UTC, eantones requested changes

2024-02-29 23:00 UTC, eantones commented on stock_barcodes_serial_source_relocation/models/stock_picking.py
> +                            )  # provar sense id # test
Is this resolved??

2024-02-29 23:00 UTC, eantones commented on stock_barcodes_serial_source_relocation/models/stock_picking.py
> +                        )  # veure que retorna, fer diferents proves
Is this resolved? Please don't leave this comments like these... Unattended and not in English

2024-02-29 23:00 UTC, eantones commented on stock_barcodes_serial_source_relocation/models/stock_picking.py
> +                            "The S/N %s has quantities in multiple locations"  # modify
Finish this "modify"

2024-02-29 23:00 UTC, eantones commented on stock_barcodes_serial_source_relocation/models/stock_picking.py
> +                        ).action_validate()
```suggestion
                if quants:
                    qty_available = quants.filtered(
                        lambda x: x.location_id == move_line.location_id
                    ).quantity
                    if (
                        float_compare(
                            move_line.qty_done,
                            qty_available,
                            precision_rounding=move_line.product_id.uom_id.rounding,
                        )
                        > 0
                    ):
                        warehouse = move_line.location_id.get_warehouse()
                        if not warehouse:
                            raise ValidationError(
                                _(
                                    "No warehouse found for the location %s"
                                    % move_line.location_id.name
                                )
                            )
                        picking_type = (
                            self.env["stock.picking.type"]
                                .search(
                                [
                                    ("warehouse_id", "in", (warehouse.id, False)),
                                    ("code", "=", "internal"),
                                    ("is_regularization", "=", True),
                                ],
                            )
                                .sorted(
                                lambda x: x.warehouse_id.id, reverse=True
                            )  # provar sense id # test
                        )
                        warehouse_ids = picking_type.mapped(
                            "warehouse_id.id"
                        )  # veure que retorna, fer diferents proves
                        if len(warehouse_ids) != len(set(warehouse_ids)):
                            raise ValidationError(
                                _(
                                    "More than one regularization picking "
                                    "type for the same warehouse %s"
                                    % move_line.location_id.name
                                )
                            )
                        if not picking_type:
                            raise ValidationError(
                                _(
                                    "No regularization picking type for location %s"
                                    % move_line.location_id.name
                                )
                            )
                        new_picking = self.env["stock.picking"].create(
                            self._prepare_relocation_picking_values(
                                move_line, picking_type[0], quants
                            )
                        )
                        new_picking.action_confirm()
                        for move in new_picking.move_lines:
                            move.move_line_ids.write(
                                self._prepare_relocation_move_line_values(
                                    move_line, new_picking, quants
                                )
                            )
                        new_picking.button_validate()
                else:
                    inventory = self.env["stock.inventory"].create(
                        self._prepare_relocation_inventory_values(move_line)
                    )
                    inventory._action_start()
                    inventory.with_context(
                        relocation_origin=self.name
                        ).action_validate()

```
It's clearer and cleaner this way

2024-03-01 17:10 UTC, eantones requested changes
On Monday, please squash all the commits into a single one

2024-03-04 08:44 UTC, FrankC013 commented
> On Monday, please squash all the commits into a single one

@eantones Done!

2024-03-04 08:57 UTC, eantones approved these changes

2024-03-08 15:21 UTC, eantones approved these changes

2024-04-12 12:57 UTC, eantones approved these changes
Good job!! 👌

2024-05-15 16:44 UTC, merged