[14.0][MIG] stock_location_localization_text
nuobit/odoo-addons pull request #43
Opened 2021-08-30 13:45 UTC by MiquelRForgeFlow

Standard migration.

2021-12-16 15:56 UTC, MiquelRForgeFlow commented
@eantones this one is ready

2021-12-21 10:18 UTC, mariadforgeflow commented
Added Localization in Location form view because in v14 it wasn't displayed.

2021-12-21 15:43 UTC, eantones requested changes

2021-12-21 15:43 UTC, eantones commented on stock_location_localization_text/i18n/es.po
> +msgstr "Pasillo (X)	"
@mariadforgeflow Please remove these spaces

2021-12-21 15:43 UTC, eantones commented on stock_location_localization_text/i18n/es.po
> +msgstr "Altura (Z)	"
These spaces too

2021-12-21 15:43 UTC, eantones commented on stock_location_localization_text/views/stock_location_views.xml
> +            </field>
Can you fix the indentation please?

2021-12-22 07:39 UTC, mariadforgeflow commented
@eantones Done!

2021-12-22 07:56 UTC, eantones approved these changes

2021-12-22 07:57 UTC, eantones commented
> @eantones Done!

Thanks! :-)

2021-12-22 07:57 UTC, merged