[14.0][IMP] connector_extension: add with delay during export and import data
nuobit/odoo-addons pull request #444
Opened 2024-12-04 16:37 UTC by FrankC013

2024-12-05 11:47 UTC, eantones requested changes
Forward port to 16.0 please

2024-12-05 11:58 UTC, FrankC013 commented
> Forward port to 16.0 please

Do it

2024-12-05 12:15 UTC, eantones approved these changes

2025-08-08 10:47 UTC, eantones commented
Not needed with #621

2025-08-08 10:47 UTC, closed without merging