[14.0][MIG] account_asset_comment
nuobit/odoo-addons pull request #57
Opened 2021-09-16 11:20 UTC by MiquelRForgeFlow

Standard migration.

`account_asset_management` dependency added in https://github.com/nuobit/odoo-addons/pull/56.

2021-12-23 14:54 UTC, ChrisOForgeFlow commented
@MiquelRForgeFlow @eantones I suggest depreciate this module, because on standard version there's a field called note

https://github.com/OCA/account-financial-tools/blob/ccd65daa77357097fe5698ca2ac77b0b75d21b8d/account_asset_management/models/account_asset.py#L96

2021-12-23 18:21 UTC, eantones commented
I agree but we need a way to migrate the data from "comment" to "note"

2021-12-23 19:11 UTC, ChrisOForgeFlow commented
I do not think that a migration script is necessary, since the field is called the same, you have to verify it in the migration process or testing the migrated base, but the type of field and the name is the same as far as I check, the only thing that change is the field label

2021-12-23 19:16 UTC, eantones commented
The new field is called "note" and the one in this module is called "comment", this is the actual field name, not the label.  I don't see your point here.

2021-12-23 19:33 UTC, ChrisOForgeFlow commented
You are right I see here

https://github.com/nuobit/odoo-addons/blob/c34c4680c6492343d0907bed608f5ae6b8afc49a/account_asset_comment/models/models.py#L11

Migration scripts is right here, I'll test migration script to check functional review

2022-02-02 09:25 UTC, mariadforgeflow approved these changes
Code review.

2022-04-25 15:53 UTC, eantones requested changes

2022-04-25 15:53 UTC, eantones commented on account_asset_comment/models/models.py
> +    note = fields.Text(string="Comment")
@MiquelRForgeFlow  It's not necessary to rename the field, the default "Note" name is fine, you can remove this.

2022-04-25 15:53 UTC, eantones commented on account_asset_comment/migrations/14.0.1.0.0/pre-migration.py
> +    comment_to_note(cr)
@MiquelRForgeFlow After the migration from "comment" to "note", the old "comment" field should be removed.

2022-04-25 16:13 UTC, MiquelRForgeFlow commented on account_asset_comment/migrations/14.0.1.0.0/pre-migration.py
> +    comment_to_note(cr)
I am not a fan of deleting columns, but I am not opposed to it. So column "comment" deleted.

2022-04-25 16:20 UTC, MiquelRForgeFlow commented
pre-commit fixed in https://github.com/nuobit/odoo-addons/pull/163.

2022-04-25 17:15 UTC, merged