12.0 mig partner name vat
nuobit/odoo-addons pull request #6
Opened 2021-04-15 09:30 UTC by VrajaTechnologies

2021-04-15 10:06 UTC, eantones requested changes
I'll merge the PR once this two minor things will be fixed.Thanks

2021-04-15 10:06 UTC, eantones commented on partner_name_vat/__manifest__.py
> +    "version": "12.0.02.03.21",
This should be 12.0.1.0.0 on the first commit of the migrations as it's described here https://github.com/nuobit/odoo-addons/wiki/Migration-to-version-12.0#tasks-to-do-in-the-migration.
@VrajaTechnologies can you please change it and push a new commit

2021-04-15 10:06 UTC, eantones commented on partner_name_vat/models/models.py
> +    # @api.multi
Remove this line

2021-04-22 19:06 UTC, eantones commented
@VrajaTechnologies Travis is red, it seems you forgot to execute pre-commit, please fix it and push it again. Thanks

2021-04-26 16:27 UTC, eantones commented
@VrajaTechnologies Please, fix Travis errors and squash the "Migration to 12.0" commits into one when you push it. It should only be 3 commits in total. Thanks

2021-04-27 13:02 UTC, VrajaTechnologies commented
Hi Eric,

We have checked in Git Hub   those 3 modules successfully build.

I have checked *partner_default_journal, *This module does not build in git
hub. *partner_default_journal *Once I have pre commit this module it was
successfully pass all cases nothing to fail in that process.

Kindly check provide us some information because I have checked different
different cases but not succeed.


Thanks In Advance

Best Regards,

Vraja Technologies

Vraja Technologies
*Odoo ERP Consultancy Service Provider*
207, Time Square, Ayodhya Chowk, • 150 feet ring road, Rajkot - 360006
*India*.
*Skype* :  *live:vrajatechnologies*
[image: email-icon]  ***@***.***
***@***.***>*
[image: website-icon]  *www.vrajatechnologies.com
<https://www.vrajatechnologies.com/>*


On Mon, 26 Apr 2021 at 21:58, Eric Antones ***@***.***> wrote:

> @VrajaTechnologies <https://github.com/VrajaTechnologies> Please, fix
> Travis errors and squash the "Migration to 12.0" commits into one when you
> push it. It should only be 3 commits in total. Thanks
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/nuobit/odoo-addons/pull/6#issuecomment-826977871>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALBYUSRQYUQSFTKYCMINSS3TKWIBPANCNFSM427CYQTQ>
> .
>

2021-04-28 13:52 UTC, eantones commented
Hi @VrajaTechnologies Travis is red, please check the errors here https://travis-ci.com/github/nuobit/odoo-addons/jobs/500520718. It seems you forgot to execute pre-commit before pushing the commit. Please fix it and push it again but, in order to avoid having duplicated "Migration" commits, also squash with the previous "Migration to 12.0" commit before doing it. The migration commit should only be one, otherwise it's difficult to see clearly the changes made. Thanks

2021-05-03 15:53 UTC, merged