12.0 mig partner default journal
nuobit/odoo-addons pull request #9
Opened 2021-04-22 17:06 UTC by VrajaTechnologies

2021-04-26 16:25 UTC, eantones commented
@VrajaTechnologies Please, squash the "Migration to 12.0" commits into one, and force push it again. It should only be 5 commits in total. Thanks

2021-04-28 13:39 UTC, eantones commented
Hi @VrajaTechnologies Travis is ok here, you just need to squash the 2 commits with the name "Migration 12.0", without it, we cannot see clearly the changes made. If you need help, we could make a call tomorrow 29th at your 14:30 (our 11:00). Let me know

2021-05-06 10:18 UTC, eantones commented
Hi @VrajaTechnologies when this PR was done and merged, I'm gonna send you more modules to migrate. Thanks

2021-06-02 10:12 UTC, eantones requested changes

2021-06-02 10:12 UTC, eantones commented on partner_default_journal/views/res_partner_views.xml
> -            <group name="acc_sale" position="inside">
@VrajaTechnologies Please, just replace "acc_sale" for "sale" and leave the rest unchanged

2021-06-02 10:12 UTC, eantones commented on partner_default_journal/views/res_partner_views.xml
> -            <group name="acc_purchase" position="inside">
@VrajaTechnologies, please, just replace "acc_purchase" for "purchase" and leave the rest unchanged

2021-06-02 10:12 UTC, eantones commented on partner_default_journal/models/account_invoice.py
> -            and not self.partner_id.purchase_journal_id
@VrajaTechnologies Why did you changed that???

2021-06-02 10:12 UTC, eantones commented on partner_default_journal/models/res_partner.py
> +        "account.journal", "Default Sale journal", domain=[("type", "=", "sale")]
With the changes made on the view I already commented, you don't need to rename the this field, please leave it as it was. The changes should be always minimal.

2021-06-02 10:12 UTC, eantones commented on partner_default_journal/models/res_partner.py
> +        "Default Purchase journal",
Same as sale journal

2021-06-21 08:16 UTC, eantones commented
@VrajaTechnologies please, squash "Migration 12.0" commits to a single one using rebase -i as we discuss in one of the calls. Thanks

2021-06-22 13:14 UTC, VrajaTechnologies commented
Hello
Rebase successfully done..please check it and let me know If anything is
missing.
Thanks


Best Regards,

Vraja Technologies

Vraja Technologies
*Odoo ERP Consultancy Service Provider*
207, Time Square, Ayodhya Chowk, • 150 feet ring road, Rajkot - 360006
*India*.
*Skype* :  *live:vrajatechnologies*
[image: email-icon]  ***@***.***
***@***.***>*
[image: website-icon]  *www.vrajatechnologies.com
<https://www.vrajatechnologies.com/>*


On Mon, 21 Jun 2021 at 13:46, Eric Antones ***@***.***> wrote:

> @VrajaTechnologies <https://github.com/VrajaTechnologies> please, squash
> "Migration 12.0" commits to a single one using rebase -i as we discuss in
> one of the calls. Thanks
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/nuobit/odoo-addons/pull/9#issuecomment-864829106>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALBYUSQKTUFMDZTLSRVIWULTT3YOFANCNFSM43M4UJKA>
> .
>

2021-06-28 10:55 UTC, eantones commented
Hi @VrajaTechnologies I still see two commits
![image](https://user-images.githubusercontent.com/10927087/123625287-e7cccd80-d80f-11eb-8ae9-7aeead100ae2.png)

 it should only be one "Migration 12.0" commit. Please squash them using rebase -i and force a push
Thanks

2021-06-28 14:04 UTC, VrajaTechnologies commented
Hi Eric,

We tried so many times to push forcefully. Also Tried to rebase the
committee but not getting successful. I got an error when I pushed
forcefully.

Can you please create a meeting with us so we will stay on call and fix it
quickly and start the next module.

It would be really helpful if you could connect with us at the meeting.

Thanks In Advance


Best Regards,

Vraja Technologies

Vraja Technologies
*Odoo ERP Consultancy Service Provider*
207, Time Square, Ayodhya Chowk, • 150 feet ring road, Rajkot - 360006
*India*.
*Skype* :  *live:vrajatechnologies*
[image: email-icon]  ***@***.***
***@***.***>*
[image: website-icon]  *www.vrajatechnologies.com
<https://www.vrajatechnologies.com/>*


On Mon, 28 Jun 2021 at 16:25, Eric Antones ***@***.***> wrote:

> Hi @VrajaTechnologies <https://github.com/VrajaTechnologies> I still see
> two commits
> [image: image]
> <https://user-images.githubusercontent.com/10927087/123625287-e7cccd80-d80f-11eb-8ae9-7aeead100ae2.png>
>
> it should only be one "Migration 12.0" commit. Please squash them using
> rebase -i and force a push
> Thanks
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/nuobit/odoo-addons/pull/9#issuecomment-869584368>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALBYUSSBXZJEFEVOVP5242DTVBIKPANCNFSM43M4UJKA>
> .
>

2021-06-29 15:54 UTC, eantones commented
Hi @VrajaTechnologies , can you send me a screenshot with the error please. Thanks

2021-06-30 10:57 UTC, VrajaTechnologies commented
Hi Nuobit/Odoo-Addons,

We tried to check the rebase module but error faced. Please find an
attachment .

Also if you have steps to resolve this issue then please let us know.

Thanks In Advance



[image: Screenshot from 2021-06-30 16-22-58.png]


[image: Screenshot from 2021-06-30 16-23-09.png]


Best Regards,

Vraja Technologies

Vraja Technologies
*Odoo ERP Consultancy Service Provider*
207, Time Square, Ayodhya Chowk, • 150 feet ring road, Rajkot - 360006
*India*.
*Skype* :  *live:vrajatechnologies*
[image: email-icon]  ***@***.***
***@***.***>*
[image: website-icon]  *www.vrajatechnologies.com
<https://www.vrajatechnologies.com/>*


On Tue, 29 Jun 2021 at 21:24, Eric Antones ***@***.***> wrote:

> Hi @VrajaTechnologies <https://github.com/VrajaTechnologies> , can you
> send me a screenshot with the error please. Thanks
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/nuobit/odoo-addons/pull/9#issuecomment-870718911>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALBYUSSA246P5ZRD5ZMECT3TVHUCJANCNFSM43M4UJKA>
> .
>

2021-06-30 11:21 UTC, eantones commented
@VrajaTechnologies the screenshots are not in the message, can you please send them again. Thanks

2021-06-30 11:27 UTC, VrajaTechnologies commented
Best Regards,

Vraja Technologies

Vraja Technologies
*Odoo ERP Consultancy Service Provider*
207, Time Square, Ayodhya Chowk, • 150 feet ring road, Rajkot - 360006
*India*.
*Skype* :  *live:vrajatechnologies*
[image: email-icon]  ***@***.***
***@***.***>*
[image: website-icon]  *www.vrajatechnologies.com
<https://www.vrajatechnologies.com/>*


On Wed, 30 Jun 2021 at 16:51, Eric Antones ***@***.***> wrote:

> @VrajaTechnologies <https://github.com/VrajaTechnologies> the screenshots
> are not in the message, can you please send them again. Thanks
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/nuobit/odoo-addons/pull/9#issuecomment-871317823>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALBYUSRQCC5JE5R63YWNDATTVL45BANCNFSM43M4UJKA>
> .
>

2021-06-30 11:30 UTC, eantones commented
@VrajaTechnologies still nothing, can you please send them by e-mail. Thanks

2021-06-30 11:33 UTC, VrajaTechnologies commented
Please find an attachment. I have attached a zip file. you need to extract
it.


Best Regards,

Vraja Technologies

Vraja Technologies
*Odoo ERP Consultancy Service Provider*
207, Time Square, Ayodhya Chowk, • 150 feet ring road, Rajkot - 360006
*India*.
*Skype* :  *live:vrajatechnologies*
[image: email-icon]  ***@***.***
***@***.***>*
[image: website-icon]  *www.vrajatechnologies.com
<https://www.vrajatechnologies.com/>*


On Wed, 30 Jun 2021 at 17:00, Eric Antones ***@***.***> wrote:

> @VrajaTechnologies <https://github.com/VrajaTechnologies> still nothing,
> can you please send them by e-mail. Thanks
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/nuobit/odoo-addons/pull/9#issuecomment-871323383>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALBYUSS7AXVVMUZK7MYBWBLTVL55NANCNFSM43M4UJKA>
> .
>

2021-06-30 12:37 UTC, eantones commented
@VrajaTechnologies I'm not receiving any attach, please send them by e-mail directly. Thanks

2021-07-08 12:24 UTC, eantones commented
Hi @VrajaTechnologies now there's 3 additional commits instead of 1. I've already done it, I'm closing this PR please check the solution on new PR https://github.com/nuobit/odoo-addons/pull/9. Thanks

2021-07-08 12:24 UTC, closed without merging